// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzyloayqrpgyxrsymgkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6eWxvYXlxcnBneXhyc3ltZ2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzMyMDgsImV4cCI6MjA2ODE0OTIwOH0.lR61PYYZlYqp-WAmQDjJkhe2BFCOSmNsT5JO5ck9GDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});